# Generated by Django 4.2 on 2023-06-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_director_photo_url'),
        ('films', '0009_alter_comment_rating'),
    ]

    operations = [
    ]
